/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jMBUBJxKv692NrSbkE8x4A

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsb0ADEcSbvaqs } from "./blank_website/PlasmicGlobalVariant__Screen"; // plasmic-import: B0aDEcSbvaqs/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsb0ADEcSbvaqs
});
