/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jMBUBJxKv692NrSbkE8x4A

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "../plasmic-root"; // plasmic-import: jMBUBJxKv692NrSbkE8x4A/projectModule

import projectcss from "../plasmic.module.css"; // plasmic-import: jMBUBJxKv692NrSbkE8x4A/projectcss

const data = {
  base: `${projectcss.plasmic_tokens}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
