// This file is automatically generated. Edits are safe but may be overwritten by generators.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Prefer runtime env (Vite prefix for client builds). Fall back to the previous hard-coded values
// so existing deploys keep working until you update envs.
const SUPABASE_URL =
  (typeof process !== "undefined" &&
    (process.env.VITE_SUPABASE_URL ||
      process.env.SUPABASE_URL ||
      process.env.SUPABASE_PROJECT_URL)) ||
  "https://paqezapusrqabwojhwyx.supabase.co";

const SUPABASE_PUBLISHABLE_KEY =
  (typeof process !== "undefined" &&
    (process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
      process.env.VITE_SUPABASE_ANON_KEY ||
      process.env.SUPABASE_PUBLISHABLE_KEY ||
      process.env.SUPABASE_ANON_KEY ||
      process.env.SUPABASE_KEY)) ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcWV6YXB1c3JxYWJ3b2pod3l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5MTcyNjEsImV4cCI6MjA3NzQ5MzI2MX0.N4jGJ7nAYz6GcAK8Ajg0v7Dy2-hhcts65iJoW6jCSV4";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    "Warning: SUPABASE_URL or SUPABASE_ANON_KEY is not set in environment variables.",
  );
}

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: typeof window !== "undefined" ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);
