// This file is automatically generated. Edits are safe but may be overwritten by generators.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Check if we should use local development mode
const USE_LOCAL_DB = import.meta.env.VITE_USE_LOCAL_DB === 'true';

if (USE_LOCAL_DB) {
  console.log('🔧 Using LOCAL DATABASE for development (set VITE_USE_LOCAL_DB=false to use Supabase)');
}

// Prefer runtime env (Vite prefix for client builds). Fall back to the previous hard-coded values
// so existing deploys keep working until you update envs.
const SUPABASE_URL =
  (typeof process !== "undefined" &&
    (process.env.VITE_SUPABASE_URL ||
      process.env.SUPABASE_URL ||
      process.env.SUPABASE_PROJECT_URL)) ||
  "https://paqezapusrqabwojhwyx.supabase.co";

const SUPABASE_PUBLISHABLE_KEY =
  (typeof process !== "undefined" &&
    (process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
      process.env.VITE_SUPABASE_ANON_KEY ||
      process.env.SUPABASE_PUBLISHABLE_KEY ||
      process.env.SUPABASE_ANON_KEY ||
      process.env.SUPABASE_KEY)) ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcWV6YXB1c3JxYWJ3b2pod3l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5MTcyNjEsImV4cCI6MjA3NzQ5MzI2MX0.N4jGJ7nAYz6GcAK8Ajg0v7Dy2-hhcts65iJoW6jCSV4";

if (!USE_LOCAL_DB && (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY)) {
  console.warn(
    "Warning: SUPABASE_URL or SUPABASE_ANON_KEY is not set in environment variables.",
  );
}

// Create either a real Supabase client or a mock client
async function createSupabaseClient() {
  try {
    if (USE_LOCAL_DB) {
      const { makeMockClient } = await import("../../lib/mockAuth");
      return makeMockClient() as any;
    }
    return createClient<Database>(
      SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY,
      {
        auth: {
          storage: typeof window !== "undefined" ? window.localStorage : undefined,
          persistSession: true,
          autoRefreshToken: true,
        },
      },
    );
  } catch (e) {
    console.error('Supabase client creation failed, falling back to stub client:', e);
    // Minimal stub to keep app rendering
    return {
      auth: {
        getSession: async () => ({ data: { session: null }, error: null }),
        onAuthStateChange: (cb: any) => {
          setTimeout(() => cb('SIGNED_OUT', null), 0);
          return { data: { subscription: { unsubscribe() {} } } };
        },
        signOut: async () => ({ error: null }),
      },
      from: () => ({ select: () => ({ maybeSingle: async () => ({ data: null, error: null }) }) }),
      rpc: async () => ({ data: null, error: null }),
      channel: () => ({ on: () => ({ subscribe: () => ({}) }) }),
      removeChannel: () => {},
      functions: { invoke: async () => ({ data: null, error: null }) },
    } as any;
  }
}

// Top-level await is supported in Vite/ESM
export const supabase: any = await createSupabaseClient();

if (import.meta.env.DEV) {
  // Simple health log so we know the client surfaced
  console.log('[SupabaseClientReady] localMode=', USE_LOCAL_DB);
}
